- name: deploy mariadb
  hosts: vm1
  gather_facts: false

  tasks:
  - name: create volume for db
    become: yes
    command: docker volume create --name mariadb_data
  - name: deploy mariadb
    become: yes
    command: docker run -d --name mariadb --env ALLOW_EMPTY_PASSWORD=yes --env MARIADB_USER=bn_wordpress --env MARIADB_PASSWORD=bitnami --env MARIADB_DATABASE=bitnami_wordpress --network host --volume mariadb_data:/bitnami/mariadb bitnami/mariadb:latest
    register: result2
  - name: setup data
    debug:
     var: result2
  - name: ensure docker-compose container is running
    become: yes
    docker_container_info:
     name: my_container
    register: result
  - name: checking result
    debug:
     var: result
