- name: deploy wordpress
  hosts: vm2
  gather_facts: false

  tasks:
  - name: create wordpress volume
    become: yes
    command: docker volume create --name wordpress_data
  - name: deploy wordpress container
    become: yes
    command: docker run -d --name wordpress -p 8080:8080 -p 8443:8443 --env ALLOW_EMPTY_PASSWORD=yes --env WORDPRESS_DATABASE_USER=bn_wordpress --env WORDPRESS_DATABASE_PASSWORD=bitnami --env WORDPRESS_DATABASE_NAME=bitnami_wordpress --network host --add-host mariadb:192.168.159.130 --volume wordpress_data:/bitnami/wordpress bitnami/wordpress:latest
    register: result
  - name: setup result
    debug: 
      var: result
  
  - name: ensure docker-compose container is running
    become: yes
    docker_container_info:
      name: my_container
    register: result2
  - name: checking result
    debug:
      var: result2
